TMSFPW-9: add landing page
noexanu/timsi-frontend pull request #2
Opened 2022-03-06 13:27 UTC by noexanu

2022-03-06 23:21 UTC, paistitshare commented on src/components/landingPage/LandingPage.styles.ts
> +  margin-top: 75px;
It's better to define paddings and margins within single css property definition like so:
`margin: 75px 0 25px;`.
margin-%sidename% definitions are also fine if they are used once per selector.

2022-03-06 23:28 UTC, paistitshare commented on src/components/landingPage/contentSection/ContentSection.styles.ts
> +export const LandingPageContentSectionHeadr = styled.h2`
LandingPageContentSectionHead**e**r

2022-03-06 23:33 UTC, paistitshare commented on src/components/landingPage/navbar/Navbar.styles.ts
> +  padding-left: 20px;
same

2022-03-06 23:34 UTC, paistitshare commented on src/components/landingPage/navbar/Navbar.styles.ts
> +  & * {
can this selector be more specific?

2022-03-06 23:36 UTC, paistitshare requested changes
Let's use "Home Page" term instead of "Landing Page"
Here's some related info for a reference: https://landingi.com/pl/tworzenie/landing-page/

2022-03-07 09:50 UTC, noexanu commented on src/components/landingPage/contentSection/ContentSection.styles.ts
> +export const LandingPageContentSectionHeadr = styled.h2`
Fixed

2022-03-07 09:55 UTC, noexanu commented on src/components/landingPage/navbar/Navbar.styles.ts
> +  padding-left: 20px;
Fixed

2022-03-07 09:56 UTC, noexanu commented on src/components/landingPage/LandingPage.styles.ts
> +  margin-top: 75px;
Fixed

2022-03-07 17:52 UTC, noexanu commented on src/components/landingPage/navbar/Navbar.styles.ts
> +  & * {
fixed

2022-03-07 18:10 UTC, paistitshare approved these changes

2022-03-07 18:12 UTC, merged